server:
  port: 9090

spring:
  application:
    name: printer-core-api
  datasource:
    url: jdbc:oracle:thin:@brlspldgdb01.dasa.net:10010:glidev01
    username: gliese
    password: gliese
    driver-class-name: oracle.jdbc.driver.OracleDriver

  cache:
    type: redis

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

---

spring:
  profiles: deploy
  datasource:
    url: ${oracleUrl}
    username: ${oracleUser}
    password: ${oraclePass}
    driver-class-name: oracle.jdbc.driver.OracleDriver
  redis:
    host: ${redisHost}
    port: ${redisPort}
    password: ${redisPass}
  rabbitmq:
    host: ${rabbitHost}
    port: ${rabbitPort}
    username: ${rabbitUser}
    password: ${rabbitPass}
