server:
  port: 9090

spring:
  application:
    name: printerserver
    jpa:
      show-sql: true
    datasource:
      url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password: sa
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
  main:
    allow-bean-definition-overriding: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

