server:
  port: 9090

spring:
  application:
    name: printerserver
  #jpa:
    #show-sql: true
    #hibernate:
      #ddl-auto: none
  datasource:
    url: jdbc:oracle:thin:@brlspldgdb01.dasa.net:10010:glidev01
    username: gliese
    password: gliese
    driver-class-name: oracle.jdbc.driver.OracleDriver

  cache:
    type: redis

management:
  endpoint:
    beans:
      enabled: true
    health:
      enabled: true
    httptrace:
      enabled: true



